Feature/add clarification ptdata 733
gematik/spec-ISiK-Vitalparameter-und-Koerpermasse pull request #137
Opened 2023-11-27 10:01 UTC by f-peverali

## Description

## Motivation and Context
PTDATA-733

## Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)?

## Checklist:

- [ ] My code follows the code style of this IG / specification.
- [ ] My change requires a change to the documentation or narrative (intend) of the IG.
- [ ] I have already updated the documentation / narrative (intend) accordingly.

2023-11-28 01:12 UTC, ylboerner requested changes

2023-11-28 01:12 UTC, ylboerner commented on ImplementationGuide/markdown/AnmerkungenMS.md
> +**Hinweis:** Siehe Beschreibung in der [FHIR Kernspezifikation]https://hl7.org/fhir/R4/observation-definitions.html#Observation.status).
```suggestion
**Hinweis:** Siehe Beschreibung in der [FHIR Kernspezifikation](https://hl7.org/fhir/R4/observation-definitions.html#Observation.status).
```

2023-11-28 01:12 UTC, ylboerner commented on ImplementationGuide/markdown/CapabilityStatement.md
> +# Konformitätserklärung [(CapabilityStatement)]https://hl7.org/fhir/R4/capabilitystatement.html)
```suggestion
# Konformitätserklärung [(CapabilityStatement)](https://hl7.org/fhir/R4/capabilitystatement.html)
```

2023-11-28 01:12 UTC, ylboerner commented on ImplementationGuide/markdown/CapabilityStatement.md
> +Jede Instanz eines bestätigungsrelevanten Systems MUSS an ihrem Endpunkt eine [CapabilityStatement]https://hl7.org/fhir/R4/capabilitystatement.html)-Ressource bereitstellen.
```suggestion
Jede Instanz eines bestätigungsrelevanten Systems MUSS an ihrem Endpunkt eine [CapabilityStatement](https://hl7.org/fhir/R4/capabilitystatement.html)-Ressource bereitstellen.
```

2023-11-28 01:12 UTC, ylboerner commented on ImplementationGuide/markdown/CapabilityStatement.md
> +Hierzu MUSS die [capabilities-Interaktion gemäß FHIR-Spezifikation]https://hl7.org/fhir/R4/http.html#capabilities) unterstützt werden.
```suggestion
Hierzu MUSS die [capabilities-Interaktion gemäß FHIR-Spezifikation](https://hl7.org/fhir/R4/http.html#capabilities) unterstützt werden.
```

2023-11-28 01:12 UTC, ylboerner commented on ImplementationGuide/markdown/Interaktionen.md
> +        finden sich in der [FHIR-Basisspezifikation - Abschnitt "Token Search"]https://hl7.org/fhir/R4/search.html#token).
```suggestion
        finden sich in der [FHIR-Basisspezifikation - Abschnitt "Token Search"](https://hl7.org/fhir/R4/search.html#token).
```

2023-11-28 01:12 UTC, ylboerner commented on ImplementationGuide/markdown/Interaktionen.md
> +        finden sich in der [FHIR-Basisspezifikation - Abschnitt "Token Search"]https://hl7.org/fhir/R4/search.html#token).
```suggestion
        finden sich in der [FHIR-Basisspezifikation - Abschnitt "Token Search"](https://hl7.org/fhir/R4/search.html#token).
```

2023-11-28 01:12 UTC, ylboerner commented on ImplementationGuide/markdown/Interaktionen.md
> +    finden sich in der [FHIR-Basisspezifikation - Abschnitt "Token Search"]https://hl7.org/fhir/R4/search.html#token).
```suggestion
    finden sich in der [FHIR-Basisspezifikation - Abschnitt "Token Search"](https://hl7.org/fhir/R4/search.html#token).
```

2023-11-28 01:13 UTC, ylboerner commented
@f-peverali Hier sind ein paar Markdown Links kaputt gegangen durch search and replace. Lass uns diese erst fixen vor der richtigen Review 👍

2024-01-03 10:47 UTC, f-peverali commented on Resources/sushi-config.yaml
> +version: 3.0.0
```suggestion
version: 3.0.1
```

2024-01-05 08:23 UTC, patrick-werner approved these changes

2024-01-05 08:40 UTC, merged