init write operations
gematik/spec-ISiK-Vitalparameter-und-Koerpermasse pull request #149
Opened 2024-02-01 13:47 UTC by f-peverali

## Description

## Motivation and Context

## How has this been tested?

## Snippets or Screenshots (if necessary):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this IG / specification.
- [ ] My change requires a change to the documentation or narrative (intend) of the IG.
- [ ] I have already updated the documentation / narrative (intend) accordingly.

2024-02-01 13:53 UTC, patrick-werner commented on ImplementationGuide/markdown/Interaktionen.md
> +    2.1. Auch Ereignis-basierte Kommunikation soll hierbei ermöglicht werden (z.B. als [Rückübermittlung Bericht aus Subsystemen](https://simplifier.net/guide/Implementierungsleitfaden-ISiK-Basismodu
```suggestion

```

2024-02-01 13:58 UTC, patrick-werner commented
sorry mein commit sollte nur eine suggestion sein, würde Composition morgen aus der Diskussion erstmal raushalten wollen.

2024-02-01 14:01 UTC, patrick-werner commented on ImplementationGuide/markdown/Interaktionen.md
> +Fraglich bleibt bei Schreiboperationen ob eine Dokumenten- oder eine REST-basierte Kommunikation anzustreben ist (für die o.g. Punkte).
wäre für mich aktuell nicht fraglich, würde hier Observation POST/PUT/
(DELETE? <- eher nicht) diskutieren

2024-02-01 14:32 UTC, f-peverali commented on ImplementationGuide/markdown/Interaktionen.md
> +Fraglich bleibt bei Schreiboperationen ob eine Dokumenten- oder eine REST-basierte Kommunikation anzustreben ist (für die o.g. Punkte).
Was wäre da die Alternative, über die man diskutieren würde? Die Kommunikation mittels "Rückübermittling" aka Composition aus Basis ?

2024-02-01 14:34 UTC, f-peverali commented on ImplementationGuide/markdown/Interaktionen.md
> +Fraglich bleibt bei Schreiboperationen ob eine Dokumenten- oder eine REST-basierte Kommunikation anzustreben ist (für die o.g. Punkte).
```suggestion
Fraglich bleibt bei Schreiboperationen ob eine Lösung über 
1) einfaches POST/PUT einer Observation oder 2) Übermittlung einer COmpoisition [analog zur Basis](https://simplifier.net/guide/Implementierungsleitfaden-ISiK-Basismodul-Stufe-3/ImplementationGuide-markdown-Datenobjekte-Datenobjekte-BerichtSubsystem?version=current) anzustreben ist (für die o.g. Punkte). 
In jedem Fall sollte es um eine REST-basierte Kommunikation gehen.
```

2024-02-01 14:35 UTC, f-peverali commented on ImplementationGuide/markdown/Interaktionen.md
> +Fraglich bleibt bei Schreiboperationen ob eine Lösung über
so ok für dich @patrick-werner ?

2024-02-12 12:35 UTC, alexzautke requested changes

2024-02-12 12:35 UTC, alexzautke commented on ImplementationGuide/markdown/Interaktionen.md
> +Alle bestätigungsrelevanten Systeme für dieses Modul nehmen die Rolle des Servers ein im Sinne eines patientenführenden Systems, an das ein Client Suchabfragen richten kann und (bei erfolgter Autoris
Wieso muss es "patientenführenden" sein?

2024-02-12 12:35 UTC, alexzautke commented on ImplementationGuide/markdown/Motivation.md
> +Um Vitalparameter und Körpermaße in verschiedenen Systemen verwenden zu können, müssen diese einheitlich und interoperabel zur Verfügung gestellt werden. Derzeit herrscht in Krankenhäusern ein reakti
> externe Geräte lassen sich nur schwer oder gar nicht mit in die Infrastruktur der Krankenhäuser einbinden

Können wir wahrscheinlich nicht belegen.

2024-02-13 08:23 UTC, f-peverali commented on ImplementationGuide/markdown/Motivation.md
> +Um Vitalparameter und Körpermaße in verschiedenen Systemen verwenden zu können, müssen diese einheitlich und interoperabel zur Verfügung gestellt werden. Derzeit herrscht in Krankenhäusern ein reakti
Das stand schon im IG (seit Stufe 2). Meine Erweiterung besteht hier im Abschnitt unten

2024-03-06 11:19 UTC, f-peverali reviewed
hier ggf. auch noch hinsichtlich ICU die Labor-Profile einarbeiten - siehe PTDATA-858

... falls in diesem Branch nicht sinnvoll, dann ein eigener

2024-03-06 13:24 UTC, patrick-werner commented
Wurde hier übernommen: https://github.com/gematik/spec-ISiK-Vitalparameter-und-Koerpermasze/pull/154 mache hier zu

2024-03-06 13:24 UTC, closed without merging