Ms fixes for tc4
gematik/spec-ISiK-Vitalparameter-und-Koerpermasse pull request #184
Opened 2024-11-21 15:59 UTC by patrick-werner

## Description
feat: added Descriptions and MS comments for all "non-MII" resources
feat: added all compatible profiles in meta.profile of all "non-Mii" resources

replaces PR: #183 (was closed due to branch rename)

2024-11-22 12:06 UTC, f-peverali commented on ImplementationGuide/markdown/ReleaseNotes.md
> +*  feat: Beschreibungen und MS-Kommentare für alle "Nicht-MII"-Ressourcen hinzugefügt https://github.com/gematik/spec-ISiK-Vitalparameter-und-Koerpermasze/pull/184
```suggestion
*  improve: Beschreibungen und MS-Kommentare für alle "Nicht-MII"-Ressourcen hinzugefügt und MS für value[x] verbessert https://github.com/gematik/spec-ISiK-Vitalparameter-und-Koerpermasze/pull/184
```

2024-11-22 12:13 UTC, f-peverali requested changes

2024-11-22 12:13 UTC, f-peverali commented on Resources/fsh-generated/resources/StructureDefinition-ISiKEKG.json
> -        "id": "Observation.component.code",
issue: MS für code muss wieder rein

2024-11-22 12:13 UTC, f-peverali commented on Resources/fsh-generated/resources/StructureDefinition-ISiKGCS.json
> -        "path": "Observation.component",
issue: MS hier auch wieder rein

2024-11-28 10:15 UTC, simoneOnFhir requested changes

2024-11-28 10:15 UTC, simoneOnFhir commented on Resources/input/fsh/ISiK-Blutdruck.fsh
> +  * dataAbsentReason MS
warum haben wir dataAbsentReason MS auf Systole und Mean? 
IIRC kann es Messungen geben, wo nur Systole, aber keine DIastole gemessen wird, daher d'accord auf Diastole. Aber gibt es auch Blutdruckmessungen mit nur Diastole?!.
MeanBP braucht m.E. keine dataAbsentResaon, da ohnehin optionales Slice.

2024-11-28 10:15 UTC, simoneOnFhir commented on Resources/input/fsh/ISiK-Ekg.fsh
> +  * ^comment = "Motivation MS: Das Feld origin definiert den Referenzpunkt und die Einheit der Messreihe, um sicherzustellen, dass die gemessenen Werte im richtigen Kontext interpretiert werden könne
Feldnamen der Lesbarkeit wegeb bitte "ticken", also "Das Feld `origin`..", "Das Feld `period`..." etc

2024-11-28 10:15 UTC, simoneOnFhir commented on Resources/input/fsh/ruleset.fsh
> +  * ^comment = "Motivation MS: Observation.status ist bereits durch die Kardinalität der Basisklasse Observation erzwungen. Dieses Feld dient der Präzisierung des Status der Untersuchung"
Zu Status bitte folgende Erläuterung ergänzen und anpassen welche Statuswerte *mindestens* implementiert werden müssen (ich denke, hier genügt "final"?)

"  **WICHTIGER Hinweis für Implementierer:**    
  * Alle server-seitigen Implementierungen MÜSSEN in der Lage sein, 
  die systemintern möglichen Statuswerte korrekt in FHIR abzubilden, mindestens jedoch <t.b.d>.
  * Alle client-seitigen Implementierungen MÜSSEN in der Lage sein, sämtliche Status-Codes zu interpretieren und dem Anwender in angemessener Form darstellen zu können, 
  beispielsweise durch Ausblenden/Durchstreichen von Ressourcen mit dem status `entered-in-error` und Ausgrauen von Ressourcen, die einen Plan- oder Entwurfs-Status haben."
"

2024-11-28 10:15 UTC, simoneOnFhir commented on Resources/input/fsh/ruleset.fsh
> +  * ^comment = "Motivation MS: Ein Vitalparameter hat immer einen Patientenbezug"
Bitte folgenden Kommentar hinzufügen/ersetzen:
"**Begründung Pflichtfeld:** Die Verlinkung auf eine Patienten-Ressource dient der technischen Zuordnung der Dokumentation zu einem Patienten 
  und ermöglicht wichtige API-Funktionen wie verkettete Suche, (Reverse-)Include etc."

2024-11-28 10:15 UTC, simoneOnFhir commented on Resources/input/fsh/ruleset.fsh
> +  * ^comment = "Motivation MS: Der Behandlungskontext ist für die Interpretation der Untersuchungsergebnisse relevant"
Bitte folgende Kommentare/Short (identisch zu Basis) übernehmen:
* encounter 
  * ^short = "Aufenthaltsbezug"
  * reference 1.. MS
    * ^short = "Encounter-Link"
    * ^comment = "**Begründung Pflichtfeld:** Die Verlinkung auf eine Encounter-Ressource dient der technischen Zuordnung der Dokumentation zu einem Aufenthalt 
    und ermöglicht wichtige API-Funktionen wie verkettete Suche, (Reverse-)Include etc.    
    **WICHTIGER Hinweis für Implementierer:** Die Zuordnung MUSS auf auf einen Encounter der Ebene &quot;Abteilungskontakt&quot; (siehe hierzu Basismodul > UseCases > Abbildung des Konstruktes &quot;Fall&quot;) erfolgen. 
    Bei der Auswahl des Encounters ist zu beachten, dass unter einer (Abrechnungs-)&quot;Fallnummer&quot; (hier: `Encounter.account`) 
    unter Umständen mehrere Encounter gruppiert sein können (z.B. stationärer Besuch mit mehreren vor- und nachstationären Aufenthalten.)"

2024-12-04 14:33 UTC, merged